import type { Edge, Node } from 'reactflow';
import type { ModuleNodeData } from '../store/editorStore';
import { getResourceName } from './resourceUtils';

export const generateHCL = (nodes: Node<ModuleNodeData>[], edges: Edge[]) => {
    let hcl = '# Generated by Terraform Visual Editor\n\n';


    nodes.forEach((node) => {
        const { type, variables } = node.data;
        const resourceName = getResourceName(node);

        // Determine if it's a resource or module (for now we treat everything as a resource or module based on type)
        // In a real app, we'd distinguish better. Here, let's assume everything starting with 'aws_' is a resource,
        // but the user asked for "Modules". 
        // If we treat them as resources:
        hcl += `resource "${type}" "${resourceName}" {\n`;

        // Find edges connected to this node's inputs
        const incomingEdges = edges.filter((edge) => edge.target === node.id);
        const connectedInputs = new Set(incomingEdges.map(edge => edge.targetHandle));

        // Add variables
        Object.entries(variables).forEach(([key, value]) => {
            if (key === '__block_label__') return; // Skip internal block label
            if (connectedInputs.has(key)) return; // Skip if connected, will be handled by edges

            let formattedValue = value;
            if (typeof value === 'string') {
                if (value.trim().startsWith('{') || value.trim().startsWith('[')) {
                    formattedValue = value;
                } else {
                    formattedValue = `"${value}"`;
                }
            }
            hcl += `  ${key} = ${formattedValue}\n`;
        });

        // Add connections (dependencies)
        incomingEdges.forEach((edge) => {
            const sourceNode = nodes.find((n) => n.id === edge.source);
            if (sourceNode) {
                const sourceName = getResourceName(sourceNode);

                // Map the connection to the input field
                // edge.targetHandle is the input name (e.g., 'vpc_id')
                // edge.sourceHandle is the output name (e.g., 'vpc_id')
                // In Terraform: vpc_id = aws_vpc.my_vpc.id

                if (edge.targetHandle) {
                    hcl += `  ${edge.targetHandle} = ${sourceNode.data.type}.${sourceName}.${edge.sourceHandle || 'id'}\n`;
                }
            }
        });

        hcl += '}\n\n';
    });

    return hcl;
};
